"""Stable error codes safe to expose in logs and user-facing diagnostics."""

from enum import StrEnum


class ErrorCode(StrEnum):
    CONFIG_INVALID = "CONFIG_INVALID"
    PROVIDER_TIMEOUT = "PROVIDER_TIMEOUT"
    PROVIDER_RATE_LIMITED = "PROVIDER_RATE_LIMITED"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    MODEL_RESPONSE_INVALID = "MODEL_RESPONSE_INVALID"
    TOOL_PERMISSION_DENIED = "TOOL_PERMISSION_DENIED"
    TOOL_TIMEOUT = "TOOL_TIMEOUT"
    TOOL_EXECUTION_FAILED = "TOOL_EXECUTION_FAILED"
    WORKSPACE_BOUNDARY_VIOLATION = "WORKSPACE_BOUNDARY_VIOLATION"
    SESSION_STATE_CORRUPT = "SESSION_STATE_CORRUPT"
    BACKGROUND_TASK_FAILED = "BACKGROUND_TASK_FAILED"
    QUEUE_EXHAUSTED = "QUEUE_EXHAUSTED"
    MEMORY_INDEX_DEGRADED = "MEMORY_INDEX_DEGRADED"
